theme: minima
title: Manchester Machine Makers
minima:
  skin: dark
  social_links:
    github: ManchesterMachineMakers
  title: Manchester Machine Makers
plugins:
  - ./_plugins/profile
exclude:
  - rakefile
  - README.md