# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Publish Site

on: [ workflow_dispatch ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: .bundle/
        # An explicit key for restoring and saving the cache
        key: bundle-folder
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Build & publish
      run: bundle exec rake
    - name: Push changes
      # You may pin to the exact commit or the version.
      # uses: actions-go/push@7ad7ce209f2a038e7bca929b7a4c92026363f856
      uses: actions-go/push@v1
      with:
        create-commit: false
